apiVersion: apps/v1
kind: Deployment
metadata:
  name: air-quality-web
  namespace: air-quality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: air-quality-web
  template:
    metadata:
      labels:
        app: air-quality-web
    spec:
      containers:
        - name: air-quality-web
          image: khomyshynd/air-quality-web:1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: REPORTS_DIR
              value: "/work/reports"
            - name: PLOTS_DIR
              value: "/work/plots"