apiVersion: v1
kind: Service
metadata:
  name: air-quality-web-service
  namespace: air-quality
spec:
  selector:
    app: air-quality-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer